services:
  cardano-node-ogmios-preprod:
    image: cardanosolutions/cardano-node-ogmios:v6.6.1_9.1.0-preprod
    profiles: ["preprod"]
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - 127.0.0.1:1338:1337
      - 3001:3000
    restart: on-failure
    volumes:
      - node-db-preprod:/db
      - node-ipc-preprod:/ipc
      - ./config/cardano-node-ogmios/preprod/topology.json:/config/cardano-node/topology.json

volumes:
  node-db-preprod:
  node-ipc-preprod:
