services:
  cardano-node-ogmios-mainnet:
    image: cardanosolutions/cardano-node-ogmios:v6.9.0_10.1.2-mainnet
    profiles: ["mainnet"]
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - 127.0.0.1:1337:1337
      - 3000:3000
    restart: on-failure
    volumes:
      - node-db-mainnet:/db
      - node-ipc-mainnet:/ipc
      - ./config/cardano-node-ogmios/mainnet/topology.json:/config/cardano-node/topology.json

volumes:
  node-db-mainnet:
  node-ipc-mainnet:
