services:
  cardano-node-ogmios-preview:
    image: cardanosolutions/cardano-node-ogmios:v6.10.0_10.1.3-preview
    profiles: ["preview"]
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - 127.0.0.1:1339:1337
      - 3002:3000
    restart: on-failure
    volumes:
      - node-db-preview:/db
      - node-ipc-preview:/ipc
      - ./config/cardano-node-ogmios/preview/topology.json:/config/cardano-node/topology.json

volumes:
  node-db-preview:
  node-ipc-preview:
