version: "3.8"

services:
  cardano-node-ogmios:
    image: cardanosolutions/cardano-node-ogmios:${OGMIOS_VERSION:-v6.0.0}_${CARDANO_NODE_VERSION:-8.7.2}-${NETWORK:-mainnet}
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - ${OGMIOS_PORT:-1337}:1337
      - ${CARDANO_NODE_PORT:-3000}:3000
    restart: on-failure
    volumes:
      - node-db:/db
      - node-ipc:/ipc
      - ./topology.json:/config/cardano-node/topology.json

volumes:
  node-db:
  node-ipc:
