version: "3.8"

services:
  cardano-node-ogmios:
    image: cardanosolutions/cardano-node-ogmios:${OGMIOS_VERSION:-v6.0.0-rc6}_${CARDANO_NODE_VERSION:-8.1.2}-${NETWORK:-mainnet}
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - 127.0.0.1:${OGMIOS_PORT:-1337}:1337
      - 3000:3000
    restart: on-failure
    volumes:
      - node-db:/db
      - node-ipc:/ipc
#      - ./config/cardano-node-ogmios/topology.json:/config/cardano-node/topology.json

  haproxy:
    image: haproxy:2.8.3
    env_file: ./.env
    environment:
      - OGMIOS_PORT=${OGMIOS_PORT:-1337}
    ports:
      - ${HAPROXY_PORT:-80}:8080
      - ${HAPROXY_SSL_PORT:-443}:8443
    shm_size: '2gb'
    volumes:
      - ./config/haproxy:/usr/local/etc/haproxy
      - /etc/ssl/xray.pem:/xray.pem
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  node-db:
  node-ipc:
