version: "3.8"

services:
  cardano-node-ogmios:
    image: cardanosolutions/cardano-node-ogmios:${OGMIOS_VERSION:-v6.0.0}_${CARDANO_NODE_VERSION:-8.7.2}-${NETWORK:-mainnet}
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - ${OGMIOS_PORT:-1337}:1337
      - ${CARDANO_NODE_PORT:-3000}:3000
    restart: on-failure
    volumes:
      - node-db:/db
      - node-ipc:/ipc
      - ./config/cardano-node-ogmios/topology.json:/config/cardano-node/topology.json

  haproxy:
    image: haproxy:2.8.3
    environment:
      - OGMIOS_PORT=${OGMIOS_PORT:-1337}
      - NETWORK=${NETWORK:-mainnet}
    ports:
      - ${HAPROXY_PORT:-80}:8080
      - ${HAPROXY_SSL_PORT:-443}:8443
    depends_on:
      - cardano-node-ogmios
    profiles: [haproxy]
    shm_size: '2gb'
    volumes:
      - ./config/haproxy:/usr/local/etc/haproxy
      #- /etc/ssl/ssl_key.pem:/ssl_key.pem
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  node-db:
  node-ipc:
